Item.create(name:'楽観(期待 + 喜び)', price:'300')
Item.create(name:'愛(喜び + 信頼)', price:'800')
Item.create(name:'服従(信頼 + 恐れ)', price:'300')
Item.create(name:'畏怖(恐れ + 驚き)', price:'300')
Item.create(name:'拒絶(驚き + 悲しみ)', price:'500')
Item.create(name:'後悔(悲しみ + 嫌悪)', price:'800')
Item.create(name:'軽蔑(嫌悪 + 怒り)', price:'500')
Item.create(name:'攻撃(怒り + 期待)', price:'500')